version: "3.9"

services:
  icecast:
    # About: https://github.com/moul/docker-icecast
    image: moul/icecast
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ICECAST_SOURCE_PASSWORD=source-password
      - ICECAST_PASSWORD=password
      - ICECAST_HOSTNAME=radiogo.example.com
    ports:
      - 8000:8000
      
  liquidsoap:
    # About: https://github.com/PhasecoreX/docker-liquidsoap
    image: ghcr.io/phasecorex/liquidsoap:latest
    volumes:
      - ./stream.liq:/conf.liq
      - ./musicdir:/media
    command: /conf.liq
